name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for submitting your question, we will deal with it as soon as possible! (ᗜ ˰ ᗜ)"
        pr-message: "Thank you very much for your contribution! We'll look into your code and get back to you as soon as possible! (≧∀≦)"
